services:
    # User
    msi_user_user_admin:
        class: %msi_user.user.admin%
        arguments: [ @msi_user.user_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    msi_user.user_manager:
        class: %msi_admin.manager.class%
        arguments: [ %fos_user.model.user.class% ]
        parent: msi_admin.manager

    # Group
    msi_user_group_admin:
        class: Msi\UserBundle\Admin\GroupAdmin
        arguments: [ @msi_user.group_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    msi_user.group_manager:
        class: %msi_admin.manager.class%
        arguments: [ %fos_user.model.group.class% ]
        parent: msi_admin.manager
